### PR TITLE
Fix pipeline misspecification error message

### LINKED ISSUE #65: Mis-specified pipeline gives the wrong error message
The following should suggest the correct pipeline name, but currently complains that `—log-level` takes only one value.

Current behavior:

```
java -jar target/scala-2.11/dagr-0.1.0-SNAPSHOT.jar --log-level=Info DnaResequencingFromFastqPipelin
...
Trying to add more than one value for the single-value option: 'log-level'
```

Desired behavior:

```
java -jar target/scala-2.11/dagr-0.1.0-SNAPSHOT.jar --log-level=Info DnaResequencingFromFastqPipelin
...
'DnaResequencingFromFastqPipelin' is not a valid command. See DagrCommandLine --help for more information.
Did you mean this?
class dagr.pipelines.DnaResequencingFromFastqPipeline
```

Of course it works when we do this:

```
java -jar target/scala-2.11/dagr-0.1.0-SNAPSHOT.jar --log-level=Info -- DnaResequencingFromFastqPipelin
...
'DnaResequencingFromFastqPipelin' is not a valid command. See DagrCommandLine --help for more information.
Did you mean this?
class dagr.pipelines.DnaResequencingFromFastqPipeline
```

### PR DESCRIPTION
**Pull request by nh13**
Fixes https://github.com/fulcrumgenomics/dagr/issues/65
1. CommandLineParser will split args by searching for similar sub-command names in the args, for args that have no leading dash.
2. Fixed bug in retrieving the remaining args in the option parser and
   friends.  The iterators will now stop after the first failure.

This commit was like pulling a loose thread, and finding a number of other issues.  I mainly found issues in the various `remaining` and `takeRemaining` methods in `sopt.parsing`.  I wanted to have any arg not consumed returned in the previously mentioned methods, including args that caused a failure.  I ended up not needing these methods in the `CommandLineParser` fix, since I simplified the usage code by having a more intelligent `splitArgs` method.

### CODE REVIEW

**Comment by nh13** [comment]
@tfenne bump

File: sopt/src/main/scala/dagr/sopt/parsing/ArgTokenCollator.scala [hunk 1]
```diff
@@ -51,31 +51,41 @@ class ArgTokenCollator(argTokenizer: ArgTokenizer) extends Iterator[Try[ArgOptio
...
+      // we would have to keep track of it.  This assumes we do not move past the first failure.
+      Failure(new OptionNameException(s"Illegal option: '$value'"))
+    case Failure(ex) =>
+      iterator.next
+      Failure(ex)
   }
 
   /** Find values with the same option name, may only be ArgValue and ArgOptionAndValue. */
-  private def addValuesWithSameName(name: String, values: ListBuffer[String]): Unit = {
+  private def addValuesWithSameName(name: String, values: mutable.ListBuffer[String]): Unit = {
```
Comment (tfenne) [inline sopt/src/main/scala/dagr/sopt/parsing/ArgTokenCollator.scala:88]: It's up to you, but I still find this redundant since a) `ListBuffer` only exists in `mutable` and b) the `Buffer` in the name clearly implies a mutable builder type.
